# Generated by Django 2.1.7 on 2019-07-14 11:46

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20190714_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to='product'),
        ),
    ]
