# Generated by Django 2.1.7 on 2019-07-15 00:43

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20190714_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=stdimage.models.StdImageField(blank=True, upload_to='product'),
        ),
    ]
